/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshop;

/**
 *
 * @author Professor Alfred
 */
public class Customersorder extends javax.swing.JFrame {

    /**
     * Creates new form Customersorder
     */
    public Customersorder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCustomersordertitle = new javax.swing.JLabel();
        lblSandwichTaken = new javax.swing.JLabel();
        lblBurgerTaken = new javax.swing.JLabel();
        lblPizzaTaken = new javax.swing.JLabel();
        lblChaominTaken = new javax.swing.JLabel();
        lblPastaTaken = new javax.swing.JLabel();
        lblColdDrinksTaken = new javax.swing.JLabel();
        cbxSandwichTaken = new javax.swing.JCheckBox();
        cbxSandwichNotTaken = new javax.swing.JCheckBox();
        cbxBurgerTaken = new javax.swing.JCheckBox();
        cbxBurgerNotTaken = new javax.swing.JCheckBox();
        cbxPizzaTaken = new javax.swing.JCheckBox();
        cbxChaominTaken = new javax.swing.JCheckBox();
        cbxPastaTaken = new javax.swing.JCheckBox();
        cbxPizzaNotTaken = new javax.swing.JCheckBox();
        cbxChaominNotTaken = new javax.swing.JCheckBox();
        cbxPastaNotTaken = new javax.swing.JCheckBox();
        cbxColdDrinksTaken = new javax.swing.JCheckBox();
        cbxColdDrinksNotTaken = new javax.swing.JCheckBox();
        btnCustomersorderBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lblCustomersordertitle.setBackground(new java.awt.Color(255, 51, 102));
        lblCustomersordertitle.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 18)); // NOI18N
        lblCustomersordertitle.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomersordertitle.setText("Customer's Order:");

        lblSandwichTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSandwichTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblSandwichTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSandwichTaken.setText("Sandwich");

        lblBurgerTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblBurgerTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblBurgerTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBurgerTaken.setText("Burger");

        lblPizzaTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPizzaTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblPizzaTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizzaTaken.setText("Pizza");

        lblChaominTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblChaominTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblChaominTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChaominTaken.setText("Chaomin");

        lblPastaTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPastaTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblPastaTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPastaTaken.setText("Pasta");

        lblColdDrinksTaken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblColdDrinksTaken.setForeground(new java.awt.Color(255, 255, 255));
        lblColdDrinksTaken.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblColdDrinksTaken.setText("Cold Drinks");

        cbxSandwichTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSandwichTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxSandwichTaken.setText("Taken");

        cbxSandwichNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxSandwichNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxSandwichNotTaken.setText("Not Taken");

        cbxBurgerTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxBurgerTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxBurgerTaken.setText("Taken");

        cbxBurgerNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxBurgerNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxBurgerNotTaken.setText("Not Taken");

        cbxPizzaTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPizzaTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxPizzaTaken.setText("Taken");

        cbxChaominTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxChaominTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxChaominTaken.setText("Taken");
        cbxChaominTaken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChaominTakenActionPerformed(evt);
            }
        });

        cbxPastaTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPastaTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxPastaTaken.setText("Taken");

        cbxPizzaNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPizzaNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxPizzaNotTaken.setText("Not Taken");

        cbxChaominNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxChaominNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxChaominNotTaken.setText("Not Taken");

        cbxPastaNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxPastaNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxPastaNotTaken.setText("Not Taken");

        cbxColdDrinksTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxColdDrinksTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxColdDrinksTaken.setText("Taken");

        cbxColdDrinksNotTaken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxColdDrinksNotTaken.setForeground(new java.awt.Color(255, 255, 255));
        cbxColdDrinksNotTaken.setText("Not Taken");

        btnCustomersorderBack.setBackground(new java.awt.Color(204, 204, 255));
        btnCustomersorderBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCustomersorderBack.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomersorderBack.setText("Back");
        btnCustomersorderBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersorderBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPastaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(cbxPastaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSandwichTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxSandwichTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCustomersordertitle, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 55, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblBurgerTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxBurgerTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPizzaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(lblChaominTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblColdDrinksTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxPizzaTaken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxChaominTaken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbxColdDrinksTaken, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxBurgerNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(cbxSandwichNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(cbxPizzaNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(cbxChaominNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(cbxPastaNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(cbxColdDrinksNotTaken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCustomersorderBack, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCustomersordertitle, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSandwichTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSandwichTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxSandwichNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblBurgerTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxBurgerTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxBurgerNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxPizzaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPizzaNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxChaominTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChaominTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbxChaominNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPizzaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxPastaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPastaTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbxPastaNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblColdDrinksTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbxColdDrinksTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cbxColdDrinksNotTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnCustomersorderBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxChaominTakenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChaominTakenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxChaominTakenActionPerformed

    private void btnCustomersorderBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersorderBackActionPerformed
        // TODO add your handling code here:
        
        ProjectMenu obj = new ProjectMenu();
        obj.setVisible(true);
    }//GEN-LAST:event_btnCustomersorderBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customersorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customersorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customersorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customersorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customersorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomersorderBack;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxBurgerNotTaken;
    private javax.swing.JCheckBox cbxBurgerTaken;
    private javax.swing.JCheckBox cbxChaominNotTaken;
    private javax.swing.JCheckBox cbxChaominTaken;
    private javax.swing.JCheckBox cbxColdDrinksNotTaken;
    private javax.swing.JCheckBox cbxColdDrinksTaken;
    private javax.swing.JCheckBox cbxPastaNotTaken;
    private javax.swing.JCheckBox cbxPastaTaken;
    private javax.swing.JCheckBox cbxPizzaNotTaken;
    private javax.swing.JCheckBox cbxPizzaTaken;
    private javax.swing.JCheckBox cbxSandwichNotTaken;
    private javax.swing.JCheckBox cbxSandwichTaken;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBurgerTaken;
    private javax.swing.JLabel lblChaominTaken;
    private javax.swing.JLabel lblColdDrinksTaken;
    private javax.swing.JLabel lblCustomersordertitle;
    private javax.swing.JLabel lblPastaTaken;
    private javax.swing.JLabel lblPizzaTaken;
    private javax.swing.JLabel lblSandwichTaken;
    // End of variables declaration//GEN-END:variables
}
