/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshop;

/**
 *
 * @author Professor Alfred
 */
public class ProjectMakerDetails extends javax.swing.JFrame {

    /**
     * Creates new form ProjectMakerDetails
     */
    public ProjectMakerDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdmin1 = new javax.swing.JButton();
        btnAdmin2 = new javax.swing.JButton();
        btnAdmin1Name = new javax.swing.JLabel();
        btnAdmin1ID = new javax.swing.JLabel();
        btnAdmin1PhoneNo = new javax.swing.JLabel();
        btnAdmin2Name = new javax.swing.JLabel();
        btnAdmin2ID = new javax.swing.JLabel();
        btnAdmin2PhoneNo = new javax.swing.JLabel();
        lbl24hoursactive = new javax.swing.JLabel();
        lblContectUs = new javax.swing.JLabel();
        btnProjectMakerDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdmin1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Professor Alfred\\Documents\\#Java\\Projectshop\\src\\projectshop\\Admin Photo\\Redwan.jpg")); // NOI18N

        btnAdmin2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Professor Alfred\\Documents\\#Java\\Projectshop\\src\\projectshop\\Admin Photo\\Pritom.jpg")); // NOI18N

        btnAdmin1Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin1Name.setText("Mohammad Radwan Shawkat");

        btnAdmin1ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin1ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin1ID.setText("192-35-2814");

        btnAdmin1PhoneNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin1PhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin1PhoneNo.setText("Phone No. 01632-108860");

        btnAdmin2Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin2Name.setText("Imran Ahmed Pritom");

        btnAdmin2ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin2ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin2ID.setText("192-35-2868");

        btnAdmin2PhoneNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdmin2PhoneNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAdmin2PhoneNo.setText("Phone No. 01729-586787");

        lbl24hoursactive.setBackground(new java.awt.Color(0, 0, 0));
        lbl24hoursactive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl24hoursactive.setForeground(new java.awt.Color(255, 51, 51));
        lbl24hoursactive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl24hoursactive.setText("24 Hours Active");

        lblContectUs.setBackground(new java.awt.Color(0, 0, 0));
        lblContectUs.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblContectUs.setForeground(new java.awt.Color(255, 0, 0));
        lblContectUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContectUs.setText("Contact us at any Need!");

        btnProjectMakerDetails.setBackground(new java.awt.Color(204, 204, 255));
        btnProjectMakerDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnProjectMakerDetails.setText("Back");
        btnProjectMakerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectMakerDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdmin1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdmin1PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdmin1ID, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(214, 214, 214)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAdmin2Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAdmin2PhoneNo, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(btnAdmin2ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdmin1)
                                .addGap(268, 268, 268)
                                .addComponent(btnAdmin2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl24hoursactive, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContectUs, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnProjectMakerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdmin1)
                    .addComponent(btnAdmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnAdmin2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdmin2ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAdmin1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdmin1ID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin1PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin2PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(lbl24hoursactive, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblContectUs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnProjectMakerDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjectMakerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjectMakerDetailsActionPerformed
        // TODO add your handling code here:
        
        ProjectMenu obj = new ProjectMenu();
        obj.setVisible(true);
        
    }//GEN-LAST:event_btnProjectMakerDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectMakerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectMakerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectMakerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectMakerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectMakerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin1;
    private javax.swing.JLabel btnAdmin1ID;
    private javax.swing.JLabel btnAdmin1Name;
    private javax.swing.JLabel btnAdmin1PhoneNo;
    private javax.swing.JButton btnAdmin2;
    private javax.swing.JLabel btnAdmin2ID;
    private javax.swing.JLabel btnAdmin2Name;
    private javax.swing.JLabel btnAdmin2PhoneNo;
    private javax.swing.JButton btnProjectMakerDetails;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl24hoursactive;
    private javax.swing.JLabel lblContectUs;
    // End of variables declaration//GEN-END:variables
}
