/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectshop;

/**
 *
 * @author Professor Alfred
 */
public class TotalBill extends javax.swing.JFrame {

    /**
     * Creates new form TotalBill
     */
    public TotalBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblSandwichTotalBill = new javax.swing.JLabel();
        lbBurgerTotalBill = new javax.swing.JLabel();
        lbPizzaTotalBill = new javax.swing.JLabel();
        lblChaominTotalBill = new javax.swing.JLabel();
        lbPastaTotalBill = new javax.swing.JLabel();
        lbColdDrinksTotalBill = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tbxSandwichTotalBillPrice = new javax.swing.JTextField();
        tbxBurgerTotalBillPrice = new javax.swing.JTextField();
        tbxPizzaTotalBillPrice = new javax.swing.JTextField();
        tbxChaominTotalBillPrice = new javax.swing.JTextField();
        tbxPastaTotalBillPrice = new javax.swing.JTextField();
        tbxColdDrinksTotalBillPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        lblTotalBill = new javax.swing.JLabel();
        lblTotalBillDispaly = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnTotalBill = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        lblSandwichTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblSandwichTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lblSandwichTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSandwichTotalBill.setText("Sandwich");

        lbBurgerTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbBurgerTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lbBurgerTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBurgerTotalBill.setText("Burger");

        lbPizzaTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPizzaTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lbPizzaTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPizzaTotalBill.setText("Pizza");

        lblChaominTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblChaominTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lblChaominTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChaominTotalBill.setText("Chaomin");

        lbPastaTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbPastaTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lbPastaTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPastaTotalBill.setText("Pasta");

        lbColdDrinksTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbColdDrinksTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lbColdDrinksTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbColdDrinksTotalBill.setText("Cold Drinks");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Total Bill");

        tbxSandwichTotalBillPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxSandwichTotalBillPriceActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(51, 51, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalBill.setText("Total Bill");

        lblTotalBillDispaly.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTotalBillDispaly.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalBillDispaly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"01", "Sandwich", "140/="},
                {"02", "Burger", "230/="},
                {"03", "Pizza", "200/="},
                {"04", "Chaomin", "150/="},
                {"05", "Pasta", "180/="},
                {"06", "Cold Drinks", " 30/="}
            },
            new String [] {
                "No.", "Items", " Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnTotalBill.setBackground(new java.awt.Color(204, 204, 255));
        btnTotalBill.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTotalBill.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalBill.setText("Back");
        btnTotalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(732, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(125, 125, 125)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSandwichTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbBurgerTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(133, 133, 133)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblChaominTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbPizzaTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbPastaTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbColdDrinksTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(146, 146, 146)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tbxColdDrinksTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxPizzaTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxBurgerTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxSandwichTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxChaominTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbxPastaTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(148, 148, 148)
                                    .addComponent(lblTotalBillDispaly, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSandwichTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbBurgerTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbxSandwichTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tbxBurgerTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbxPizzaTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tbxChaominTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblChaominTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbPizzaTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPastaTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxPastaTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(lbColdDrinksTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tbxColdDrinksTotalBillPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(lblTotalBillDispaly, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnTotalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        //Taking Input:
        String StrSandwich = tbxSandwichTotalBillPrice.getText();
        int Sandwich = Integer.parseInt(StrSandwich);
        
        String StrBurger = tbxBurgerTotalBillPrice.getText();
        int Burger = Integer.parseInt(StrBurger);
                
        String StrPizza = tbxPizzaTotalBillPrice.getText();
        int Pizza = Integer.parseInt(StrPizza);
        
        String StrChaomin = tbxChaominTotalBillPrice.getText();
        int Chaomin = Integer.parseInt(StrChaomin);
        
        String StrPasta = tbxPastaTotalBillPrice.getText();
        int Pasta = Integer.parseInt(StrPasta);
        
        String StrColdDrinks = tbxColdDrinksTotalBillPrice.getText();
        int ColdDrinks = Integer.parseInt(StrColdDrinks);
        
        //Add those number:
        int sum = Sandwich + Burger + Pizza + Chaomin + Pasta + ColdDrinks;
        
        //Result Show:
        lblTotalBillDispaly.setText(String.valueOf(sum));
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnTotalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalBillActionPerformed
        // TODO add your handling code here:
        
        ProjectMenu obj = new ProjectMenu();
        obj.setVisible(true);
    }//GEN-LAST:event_btnTotalBillActionPerformed

    private void tbxSandwichTotalBillPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxSandwichTotalBillPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxSandwichTotalBillPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TotalBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TotalBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnTotalBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbBurgerTotalBill;
    private javax.swing.JLabel lbColdDrinksTotalBill;
    private javax.swing.JLabel lbPastaTotalBill;
    private javax.swing.JLabel lbPizzaTotalBill;
    private javax.swing.JLabel lblChaominTotalBill;
    private javax.swing.JLabel lblSandwichTotalBill;
    private javax.swing.JLabel lblTotalBill;
    private javax.swing.JLabel lblTotalBillDispaly;
    private javax.swing.JTextField tbxBurgerTotalBillPrice;
    private javax.swing.JTextField tbxChaominTotalBillPrice;
    private javax.swing.JTextField tbxColdDrinksTotalBillPrice;
    private javax.swing.JTextField tbxPastaTotalBillPrice;
    private javax.swing.JTextField tbxPizzaTotalBillPrice;
    private javax.swing.JTextField tbxSandwichTotalBillPrice;
    // End of variables declaration//GEN-END:variables
}
